const enemies = [
    {
        name: 'Slime Water',
        path: 'slime-blue',
        type: 'water',
        hp: 600,
        dmg: 90,
        armor: 20,
        exp: 20,
        rarity: 150,
    },
    {
        name: 'Slime Grass',
        path: 'slime-green',
        type: 'plant',
        hp: 600,
        dmg: 90,
        armor: 20,
        exp: 20,
        rarity: 100,
    },
    {
        name: 'Slime Gold',
        path: 'slime-gold',
        type: 'iron',
        hp: 600,
        dmg: 90,
        armor: 20,
        exp: 20,
        rarity: 50,
    },
    {
        name: 'Slime Fire',
        path: 'slime-red',
        type: 'fire',
        hp: 600,
        dmg: 90,
        armor: 20,
        exp: 20,
        rarity: 15,
    },
    {
        name: 'Slime Mystic',
        path: 'slime-purple',
        type: 'magic',
        hp: 600,
        dmg: 90,
        armor: 20,
        exp: 20,
        rarity: 5,
    },
    // {
    // 	name: 'Evil Tree',
    // 	path: 'eviltree',
    // 	type: 'plant',
    // 	hp: 1200,
    // 	dmg: 60,
    // 	exp: 30,
    // 	rarity: 100,
    // },
]

export default enemies
